### ISSUE TITLE
Theme too heavy for a Raspberry Pi

### ISSUE THREAD

**Issue by MaximLopez** [jdorigao/es-theme-alekfull#1]
Hello, I'm contacting you, because I discovered a problem when using your theme on a Raspberry Pi3B / 3B +. Indeed, the images are too compressed and the DPIs are too high for this material. I allowed myself to make a version with downsampling (72dpi) to perform tests and with this DPI, the theme works perfectly! Can you solve this problem if you have the time? Here is a link from my GitHub repository with the downsampling : https://github.com/MaximLopez/alekfull-lite

**Comment by jdorigao** [comment]
Thanks for the report!
